---
title: ' Forecasting applications '
author: "Derya Kitis - IE360 - Fall 2020"
---
  ```{r,echo=FALSE,results="hide"}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
```

1.[Time series forecasting using ARIMA models](https://blogs.oracle.com/datascience/introduction-to-forecasting-with-arima-in-r)

This example is important because it introduces the forecasting methodology using ARIMA models in R. The steps are:
1.	Examine Your Data
2.	Decompose Your Data
3.	Stationarity
4.	Autocorrelations and Choosing Model Order
5.	Fitting an ARIMA model
6.	Evaluate and Iterate

2.[Application Of Time Series Analysis In Financial Economics](https://medium.com/@statswork/application-of-time-series-analysis-in-financial-economics-c1a7e1b69d04)

Time series in financial economics are highly important to analyze the trend or pattern of the variable of interest using an appropriate model. Any financial organization relies on time series forecasting to build their marketing strategy to meet the customer’s needs.

In the first example, the daily values of the data with the time factors available between 2010 and 2016 from the Yahoo Finance repository is analyzed, and also another dataset from Kaggle is used to forecast the market sentiment.
The second example clearly depicts the trend in the price of the stock and this trend may be helpful in predicting future stock values using suitable models.
In the third example, the trend of the sales and tractor demand in a manufacturing company has been analyzed. If the company is interested in understanding the impact of marketing efforts on sales; the pattern of the sales and demand can be viewed using a well-known ARIMA model and the sales/demand can be predicted for the upcoming years.

3.[ Time series model for forecasting the number of new admission inpatients](https://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/s12911-018-0616-8)

Since hospital crowding is a rising problem, effective predicting and detecting managment is crucial and can be helpful to reduce crowding.

In the application, the single seasonal ARIMA (SARIMA), NARNN and the hybrid SARIMA-NARNN model is used to fit and forecast the monthly and daily number of new admission inpatients. The root mean square error, mean absolute error and mean absolute percentage error were used to compare the forecasting performance among the three models. 

4.[Time-series models for cloud workload prediction](https://ieeexplore.ieee.org/document/7987292)

Dynamic cloud workloads necessitate forecasting methodologies for accurate resource provisioning affecting both cloud providers and clients. This application's importance stems from the fact that it is focusing on forecasting in the cloud in order to understand its underlying workload dynamics. 

This application involves the analyze of recent workload traces and discovers characteristics that are not adequately captured by traditional linear & nonlinear models employed for forecasting in the cloud. This research involves a comprehensive statistical analysis of several workloads realized from production cloud environments.

5.[Rainfall Time Series Analysis and Forecasting](https://towardsdatascience.com/rainfall-time-series-analysis-and-forecasting-87a29316494e)

This application is so important because in the tropics region which several countries only had two seasons in a year, many countries which rely so much on agricultural commodities will need to forecast rainfall in term to decide the best time to start planting their products and maximizing their harvest. 

In this article, Rainfall forecasting in Banten Province located in Indonesia is done by using historical rainfall data and using R Language. The steps are as follows: importing and selecting data, exploratory time series data analysis, decomposition, seasonality analysis, choosing the right model and building the model.

